CC = gcc
CFLAGS = -c -wall

all: SatSutSec KofakHesap2x2 determinant3x3

SatSutSec: SatSutSec.c
	$(CC) SatSutSec.c -o SatSutSec

KofakHesap2x2: KofakHesap2x2.c
	$(CC) KofakHesap2x2.c -o KofakHesap2x2

determinant3x3: determinant3x3.c
	$(CC) determinant3x3.c -o determinant3x3

clean:
	rm -rf *.o main

